# Generated by Django 2.2.4 on 2019-11-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190522_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInputs',
        ),
    ]
