# Generated by Django 2.2.4 on 2019-11-24 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='mod_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
