# Generated by Django 2.2.7 on 2019-12-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191124_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
