# Generated by Django 2.2.7 on 2019-12-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='liked',
        ),
    ]
