# Generated by Django 2.1.1 on 2018-09-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_date',
            new_name='product_date',
        ),
    ]
