# Generated by Django 2.1.1 on 2018-09-29 17:55

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180929_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Best practice is to not change this', populate_from=('title',), unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 23, 25, 23, 53581)),
        ),
    ]
