# Generated by Django 2.1.1 on 2018-09-30 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180930_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 21, 48, 32, 705150)),
        ),
    ]
