# Generated by Django 2.1.8 on 2019-05-22 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190522_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 12, 51, 48, 244326)),
        ),
    ]
