# Generated by Django 2.1.8 on 2019-05-22 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190522_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_date',
        ),
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 15, 6, 2, 911934)),
        ),
    ]
